services:
  cookie-api:
    build: .
    restart: always
    #network_mode: "host"
    ports:
      - "8002:8002"
    #volumes:
    #  - /data:/app/data/
    #env_file:
    #  - .env
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONIOENCODING=UTF-8
